name: CI/CD Actions
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        env:
          ENV: production
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          EMAIL_VERIFICATION_URL: ${{ secrets.EMAIL_VERIFICATION_URL }}
          RESET_PASSWORD_URL: ${{ secrets.RESET_PASSWORD_URL }}
          SOCIAL_SIGN_UP_PASSWORD_KEY: ${{ secrets.SOCIAL_SIGN_UP_PASSWORD_KEY }}
          GMAIL_ACCOUNT: ${{ secrets.GMAIL_ACCOUNT }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          OAUTH_REFRESH_TOKEN: ${{ secrets.OAUTH_REFRESH_TOKEN }}
          GOOGLE_CLOUD_STORAGE_BUCKET: ${{ secrets.GOOGLE_CLOUD_STORAGE_BUCKET }}
          VERSION: ${{ secrets.VERSION }}
        run: |
          docker-compose build
          docker-compose push

      - name: Update Dockerrun.aws.json
        run: echo "`jq '.containerDefinitions[0].image = "jwoonim/idea-organizer:${{ secrets.VERSION }}"' Dockerrun.aws.json`" > Dockerrun.aws.json

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: idea-organizer
          environment_name: Ideaorganizer-env
          version_label: ${{ secrets.VERSION }}
          region: us-west-2
          deployment_package: deploy.zip